### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by felciano** [JonnyFunFun/TPy#1]
Hi --

Just came across your library -- looks like just what I've been looking for to do some TP automation! Are you still developing it actively? Any chance of getting support for Iterations and UserStories?

Ramon

**Comment by JonnyFunFun** [comment]
Hi Ramon!  Yes, the library is still being developed - just not as quickly as I'd like to do it.  I put some time in here and there, but as you can probably see from the history there are some periods where months go by before I get a chance to work on it again.  Of course UserStories and Iterations will be supported in the end - my plans are to have 100% coverage of the API.

Feel free to star/watch the repository, and if you're looking to contribute I'd be happy to welcome you on-board!
- Jonathan

**Comment by felciano** [comment]
Cool! I wish my git chops were stronger else I'd fork and try contributing some stuff as well. I'm coming from SVN into Mercurial and git just makes my brain hurt!

**Comment by CHANDANVARMA** [comment]
Hello Guys,

I am not able to install the tpy on following commands;
pip install tpy
easy_install tpy
Then i got the error "distribution is not found"

If i am downloading the zip file and run the command 
python setup.py install
Again i got following error:-
AttributeError: 'NoneType' object has no attribute 'group'

Please resolve the issue and share with me any other alternate solutions.

**Comment by ssbarnea** [comment]
If after so much time we still do not have anything published un pypi, I would call it abandonware.

**Comment by JonnyFunFun** [comment]
@ssbarnea that's pretty much about what it is now that I have very little time to dedicate to it.  For now you can more or less consider this repository as a placeholder.
